export const productsData = {
  'Flowers & Bouquets': {
    'Bouquet Collection': [
      { id: 1, name: 'Minimal Smiley', price: '₹850', image: '/images/products/img-029.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Pink', images: ['/images/products/img-029.png', '/images/products/img-045.png', '/images/products/img-056.png'], description: 'Cute minimal smiley bouquet', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 2, name: 'Blush Blossom', price: '₹850', image: '/images/products/img-055.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Pink/White', images: ['/images/products/img-055.png', '/images/products/img-027.png', '/images/products/img-109.png'], description: 'Delicate pink and white blossoms', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 3, name: 'Lily World (Medium)', price: '₹1670', image: '/images/products/img-026.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Purple/White', images: ['/images/products/img-026.png', '/images/products/img-077.png', '/images/products/img-075.png'], description: 'Medium lily flower arrangement', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 4, name: 'Smiley Bouquet', price: '₹1100', image: '/images/products/img-110.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Multiple', images: ['/images/products/img-110.png', '/images/products/img-076.png', '/images/products/img-086.png'], description: 'Happy smiley faces in bouquet form', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 5, name: 'Love Struck Bouquet', price: '₹720', image: '/images/products/img-106.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Red/White', images: ['/images/products/img-106.png', '/images/products/img-083.png', '/images/products/img-131.png'], description: 'Love-themed romantic bouquet', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 6, name: 'Golden Meadow', price: '₹1200', image: '/images/products/img-107.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Yellow/White', images: ['/images/products/img-107.png', '/images/products/img-085.png', '/images/products/img-065.png'], description: 'Golden meadow with sunflowers', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 7, name: 'Sunshine Bloom', price: '₹800', image: '/images/products/img-068.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Yellow/Pink', images: ['/images/products/img-068.png', '/images/products/img-067.png', '/images/products/img-084.png'], description: 'Bright sunshine flower bouquet', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 8, name: 'Tulip Dreams', price: '₹950', image: '/images/products/img-097.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Purple/White', images: ['/images/products/img-097.png', '/images/products/img-108.png', '/images/products/img-114.png'], description: 'Dreamy tulip arrangements', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 9, name: 'Sunny Garden', price: '₹900', image: '/images/products/img-111.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Yellow/White', images: ['/images/products/img-111.png', '/images/products/img-119.png', '/images/products/img-125.png'], description: 'Sunny garden flower collection', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 10, name: 'Single Sunflower', price: '₹350', image: '/images/products/img-126.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Yellow', images: ['/images/products/img-126.png', '/images/products/img-127.png', '/images/products/img-128.png'], description: 'Single beautiful sunflower', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
    ],
    'Premium Bouquet Collection': [
      { id: 11, name: 'Sunflower Bouquet (Large)', price: '₹1550', image: '/images/products/img-129.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Yellow', images: ['/images/products/img-129.png', '/images/products/img-130.png', '/images/products/img-132.png'], description: 'Large premium sunflower bouquet', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 12, name: 'Maroon Lily Duo', price: '₹999', image: '/images/products/img-133.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Red/Maroon', images: ['/images/products/img-133.png', '/images/products/img-134.png', '/images/products/img-135.png'], description: 'Two maroon lilies together', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 13, name: 'Smiley Bouquet (Medium)', price: '₹1630', image: '/images/products/img-136.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Purple/Yellow', images: ['/images/products/img-136.png', '/images/products/img-137.png', '/images/products/img-138.png'], description: 'Medium premium smiley bouquet', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 14, name: 'Golden Sunshine', price: '₹1250', image: '/images/products/img-139.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Yellow', images: ['/images/products/img-139.png', '/images/products/img-140.png', '/images/products/img-141.png'], description: 'Golden sunshine premium collection', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 15, name: 'Maroon Lily Garden', price: '₹1550', image: '/images/products/img-142.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Maroon/White', images: ['/images/products/img-142.png', '/images/products/img-143.png', '/images/products/img-144.png'], description: 'Maroon lily garden arrangement', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 16, name: 'Red Rose Love', price: '₹1650', image: '/images/products/img-145.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Red', images: ['/images/products/img-145.png', '/images/products/img-029.png', '/images/products/img-045.png'], description: 'Premium red roses arrangement', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 17, name: 'Blue Paradise Bouquet (Large)', price: '₹2100', image: '/images/products/img-056.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Blue/White', images: ['/images/products/img-056.png', '/images/products/img-055.png', '/images/products/img-027.png'], description: 'Large blue paradise collection', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 18, name: 'Premium Smiley Bouquet (Large)', price: '₹1899', image: '/images/products/img-109.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Purple/Yellow', images: ['/images/products/img-109.png', '/images/products/img-026.png', '/images/products/img-077.png'], description: 'Large premium smiley arrangement', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 19, name: 'Purple Garden Elegance', price: '₹2500', image: '/images/products/img-075.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Purple/White', images: ['/images/products/img-075.png', '/images/products/img-110.png', '/images/products/img-076.png'], description: 'Elegant purple garden bouquet', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 20, name: 'Bluebell Dreams', price: '₹1780', image: '/images/products/img-086.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Blue/White', images: ['/images/products/img-086.png', '/images/products/img-106.png', '/images/products/img-083.png'], description: 'Dreamy bluebell collection', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
    ],
    'Budget Picks': [
      { id: 21, name: 'Bloom Lily (Medium)', price: '₹600', image: '/images/products/img-131.png', category: 'Flowers & Bouquets', subcategory: 'Budget Picks', color: 'Purple/Multiple', images: ['/images/products/img-131.png', '/images/products/img-107.png', '/images/products/img-085.png'], description: 'Medium bloom lily flower', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 22, name: '3D Rose (Small)', price: '₹320', image: '/images/products/img-065.png', category: 'Flowers & Bouquets', subcategory: 'Budget Picks', color: 'Purple', images: ['/images/products/img-065.png', '/images/products/img-068.png', '/images/products/img-067.png'], description: 'Small 3D rose design', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 23, name: 'Minimal Rose', price: '₹280', image: '/images/products/img-084.png', category: 'Flowers & Bouquets', subcategory: 'Budget Picks', color: 'Ivory & Crimson', images: ['/images/products/img-084.png', '/images/products/img-097.png', '/images/products/img-108.png'], description: 'Minimal rose design', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 24, name: 'Blossom Tulip', price: '₹299', image: '/images/products/img-114.png', category: 'Flowers & Bouquets', subcategory: 'Budget Picks', color: 'Purple/Multiple shades', images: ['/images/products/img-114.png', '/images/products/img-111.png', '/images/products/img-119.png'], description: 'Our quiet bestseller - Blossom tulip', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
    ],
  },
  'Accessories': {
    'Hair & Occasion': [
      { id: 25, name: 'Mohabbat Gajra', price: '₹199', image: '/images/products/img-125.png', category: 'Accessories', subcategory: 'Hair & Occasion', color: 'Cream', images: ['/images/products/img-125.png', '/images/products/img-126.png', '/images/products/img-127.png'], description: 'For the softest of occasions - Thin gajra with green cord', tat: '1-2 hours', care: 'Handle with care' },
      { id: 26, name: 'Pinkish Parandi', price: '₹280', image: '/images/products/img-128.png', category: 'Accessories', subcategory: 'Hair & Occasion', color: 'Pink/White', images: ['/images/products/img-128.png', '/images/products/img-129.png', '/images/products/img-130.png'], description: 'Playful pink tassels - For weddings & festivities', tat: '2-3 hours', care: 'Handle with care' },
      { id: 27, name: 'Ivory Bloom Tie', price: '₹120', image: '/images/products/img-132.png', category: 'Accessories', subcategory: 'Hair & Occasion', color: 'White', images: ['/images/products/img-132.png', '/images/products/img-133.png', '/images/products/img-134.png'], description: 'Hair tie - Cluster of ivory blossoms', tat: '1-2 hours', care: 'Handle with care' },
      { id: 28, name: 'Rose Gajra', price: '₹280', image: '/images/products/img-135.png', category: 'Accessories', subcategory: 'Hair & Occasion', color: 'Red', images: ['/images/products/img-135.png', '/images/products/img-136.png', '/images/products/img-137.png'], description: 'Rosy red gajra - For weddings & festivities', tat: '2-3 hours', care: 'Handle with care' },
      { id: 29, name: 'Mohabbat Gajra 2.0', price: '₹299', image: '/images/products/img-138.png', category: 'Accessories', subcategory: 'Hair & Occasion', color: 'Maroon/White', images: ['/images/products/img-138.png', '/images/products/img-139.png', '/images/products/img-140.png'], description: 'Heavy creamy florals - For special occasions', tat: '2-3 hours', care: 'Handle with care' },
    ],
    'Scrunchies & Everyday': [
      { id: 30, name: 'Blooming Scrunchy', price: '₹220', image: '/images/products/img-141.png', category: 'Accessories', subcategory: 'Scrunchies & Everyday', color: 'Multiple', images: ['/images/products/img-141.png', '/images/products/img-142.png', '/images/products/img-143.png'], description: 'Fluffy petals bloom around wrist - Custom colors available', tat: '1-2 hours', care: 'Gentle wash' },
      { id: 31, name: 'Hearty Scrunchy', price: '₹199', image: '/images/products/img-144.png', category: 'Accessories', subcategory: 'Scrunchies & Everyday', color: 'Pink', images: ['/images/products/img-144.png', '/images/products/img-145.png', '/images/products/img-029.png'], description: 'Sweet soft gentle petals - Custom colors available', tat: '1-2 hours', care: 'Gentle wash' },
      { id: 32, name: 'Flowery Scrunchy', price: '₹299', image: '/images/products/img-045.png', category: 'Accessories', subcategory: 'Scrunchies & Everyday', color: 'Purple', images: ['/images/products/img-045.png', '/images/products/img-056.png', '/images/products/img-055.png'], description: 'Statement scrunchy with ruffle-garden feel - Custom colors available', tat: '1-2 hours', care: 'Gentle wash' },
      { id: 33, name: 'Pinteresty Basic', price: '₹99', image: '/images/products/img-027.png', category: 'Accessories', subcategory: 'Scrunchies & Everyday', color: 'Neutral', images: ['/images/products/img-027.png', '/images/products/img-109.png', '/images/products/img-026.png'], description: 'Everyday scrunchies in go-with-everything neutrals - Custom colors available', tat: '1-2 hours', care: 'Gentle wash' },
      { id: 34, name: 'Minimal Scrunchy', price: '₹79', image: '/images/products/img-077.png', category: 'Accessories', subcategory: 'Scrunchies & Everyday', color: 'Multiple', images: ['/images/products/img-077.png', '/images/products/img-075.png', '/images/products/img-110.png'], description: 'Simple soft endlessly wearable - Custom colors available', tat: '1-2 hours', care: 'Gentle wash' },
    ],
  },
  'Home Decor': {
    'Decor Collection': [
      { id: 35, name: 'Daisy Bookmark', price: '₹99', image: '/images/products/img-076.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'White/Yellow', images: ['/images/products/img-076.png', '/images/products/img-086.png', '/images/products/img-106.png'], description: 'Reading companion - Tiny crochet daisy to hold your page', tat: '2-3 hours', care: 'Dust gently' },
      { id: 36, name: 'Sunflower Pot', price: '₹380', image: '/images/products/img-083.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Yellow', images: ['/images/products/img-083.png', '/images/products/img-131.png', '/images/products/img-107.png'], description: 'Desk bloom - A sunflower that never fades in cosy knit pot', tat: '3-4 hours', care: 'Dust gently' },
      { id: 37, name: 'Lily Flower Pot', price: '₹520', image: '/images/products/img-085.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Multiple', images: ['/images/products/img-085.png', '/images/products/img-065.png', '/images/products/img-068.png'], description: 'Desk bloom - 7-8 inch tall - Multiple colors available', tat: '4-5 hours', care: 'Dust gently' },
      { id: 38, name: 'Smiley Bag Charm', price: '₹380', image: '/images/products/img-067.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Multi', images: ['/images/products/img-067.png', '/images/products/img-084.png', '/images/products/img-097.png'], description: 'Cute bag charm accessory', tat: '2-3 hours', care: 'Handle with care' },
      { id: 39, name: 'Bush Bloom Curtain Holder', price: '₹730', image: '/images/products/img-108.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Multiple', images: ['/images/products/img-108.png', '/images/products/img-114.png', '/images/products/img-111.png'], description: 'Pair with tassels - Soft marble printed large flower', tat: '4-5 hours', care: 'Dust gently' },
      { id: 40, name: 'Sunflower Curtain Holder', price: '₹699', image: '/images/products/img-119.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Yellow', images: ['/images/products/img-119.png', '/images/products/img-125.png', '/images/products/img-126.png'], description: 'Pair - Trailing stems - Cascading sunflowers on trailing stem', tat: '4-5 hours', care: 'Dust gently' },
      { id: 41, name: 'Hearty Jewellery Basket', price: '₹449', image: '/images/products/img-127.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Crimson', images: ['/images/products/img-127.png', '/images/products/img-128.png', '/images/products/img-129.png'], description: 'Heart-shape - Keeping-place for rings earrings small treasures', tat: '3-4 hours', care: 'Dust gently' },
      { id: 42, name: 'Teddy Specs Holder', price: '₹299', image: '/images/products/img-130.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Brown/Cream', images: ['/images/products/img-130.png', '/images/products/img-132.png', '/images/products/img-133.png'], description: 'Bedside buddy - Gives your glasses a soft place to rest', tat: '2-3 hours', care: 'Handle with care' },
    ],
  },
  'Signature Combos': {
    'Curated Bundles': [
      { id: 43, name: 'Mini Bloom Combo', price: '₹499', image: '/images/products/img-134.png', category: 'Signature Combos', subcategory: 'Curated Bundles', color: 'Customisable', images: ['/images/products/img-134.png', '/images/products/img-135.png', '/images/products/img-136.png'], description: 'Cute - Budget - Small gifting. Flower + filler - one flower of your choice + complimentary filler', tat: 'Custom', care: 'Handle with care' },
      { id: 44, name: 'Classic Love Combo', price: '₹799', image: '/images/products/img-137.png', category: 'Signature Combos', subcategory: 'Curated Bundles', color: 'Multiple', images: ['/images/products/img-137.png', '/images/products/img-138.png', '/images/products/img-139.png'], description: 'Balanced - Full - Gifting. Three flowers + complimentary premium fillers + leaf detailing', tat: 'Custom', care: 'Handle with care' },
      { id: 45, name: 'Premium Combo', price: '₹1299', image: '/images/products/img-140.png', category: 'Signature Combos', subcategory: 'Curated Bundles', color: 'Multiple', images: ['/images/products/img-140.png', '/images/products/img-141.png', '/images/products/img-142.png'], description: 'Luxury - Statement Gifting. 3-4 flowers including Premium centrepiece + 2 supporting flowers + complimentary premium fillers + leaf styling', tat: 'Custom', care: 'Handle with care' },
      { id: 46, name: 'Maa Custom Combo', price: 'Custom', image: '/images/products/img-143.png', category: 'Signature Combos', subcategory: 'Curated Bundles', color: 'Fully Customisable', images: ['/images/products/img-143.png', '/images/products/img-144.png', '/images/products/img-145.png'], description: 'Custom Design. Mix your favorite flowers & fillers - fully customizable to your preference', tat: 'Custom', care: 'Handle with care' },
    ],
  },
};

export const getAllProducts = () => {
  const allProducts = [];
  Object.values(productsData).forEach(category => {
    Object.values(category).forEach(subcategory => {
      allProducts.push(...subcategory);
    });
  });
  return allProducts;
};

export const getProductsByCategory = (categoryName) => {
  return productsData[categoryName] || {};
};
