export const productsData = {
  'Flowers & Bouquets': {
    'Bouquet Collection': [
      { id: 1, name: 'Minimal Smiley', price: '₹850', image: '/images/products/Bouquet_Minimal Smiley.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Pink', images: ['/images/products/Bouquet_Minimal Smiley.png', '/images/products/img-045.png', '/images/products/img-056.png'], description: 'Cute minimal smiley bouquet', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 2, name: 'Blush Blossom', price: '₹850', image: '/images/products/Bouquet_Blush Blossom.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Pink/White', images: ['/images/products/Bouquet_Blush Blossom.png', '/images/products/img-027.png', '/images/products/img-109.png'], description: 'Delicate pink and white blossoms', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 3, name: 'Lily World (Medium)', price: '₹1670', image: '/images/products/Bouquet_ Lily World(Medium).png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Purple/White', images: ['/images/products/Bouquet_ Lily World(Medium).png', '/images/products/img-077.png', '/images/products/img-075.png'], description: 'Medium lily flower arrangement', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 4, name: 'Smiley Bouquet', price: '₹1100', image: '/images/products/Bouquet_Smiley Bouquet.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Multiple', images: ['/images/products/Bouquet_Smiley Bouquet.png', '/images/products/img-076.png', '/images/products/img-086.png'], description: 'Happy smiley faces in bouquet form', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 5, name: 'Love Struck Bouquet', price: '₹720', image: '/images/products/Bouquet_Love Struck Bouquet.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Red/White', images: ['/images/products/Bouquet_Love Struck Bouquet.png', '/images/products/img-083.png', '/images/products/img-131.png'], description: 'Love-themed romantic bouquet', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 6, name: 'Golden Meadow', price: '₹1200', image: '/images/products/Bouquet_Golden Meadow.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Yellow/White', images: ['/images/products/Bouquet_Golden Meadow.png', '/images/products/img-085.png', '/images/products/img-065.png'], description: 'Golden meadow with sunflowers', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 7, name: 'Sunshine Bloom', price: '₹800', image: '/images/products/Bouquet_Sunshine Bloom.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Yellow/Pink', images: ['/images/products/Bouquet_Sunshine Bloom.png', '/images/products/img-067.png', '/images/products/img-084.png'], description: 'Bright sunshine flower bouquet', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 8, name: 'Tulip Dreams', price: '₹950', image: '/images/products/Bouquet_Tulip Dream.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Purple/White', images: ['/images/products/Bouquet_Tulip Dream.png', '/images/products/img-108.png', '/images/products/img-114.png'], description: 'Dreamy tulip arrangements', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 9, name: 'Sunny Garden', price: '₹900', image: '/images/products/Bouquet_Sunny Garden.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Yellow/White', images: ['/images/products/Bouquet_Sunny Garden.png', '/images/products/img-119.png', '/images/products/img-125.png'], description: 'Sunny garden flower collection', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
      { id: 10, name: 'Single Sunflower', price: '₹350', image: '/images/products/Bouquet_ Single Sunflower.png', category: 'Flowers & Bouquets', subcategory: 'Bouquet Collection', color: 'Yellow', images: ['/images/products/Bouquet_ Single Sunflower.png', '/images/products/img-127.png', '/images/products/img-128.png'], description: 'Single beautiful sunflower', tat: '3-4 hours', care: 'Keep away from direct sunlight' },
    ],
    'Premium Bouquet Collection': [
      { id: 11, name: 'Sunflower Bouquet (Large)', price: '₹1550', image: '/images/products/PremiumBouquet_Sunflower Bouquet.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Yellow', images: ['/images/products/PremiumBouquet_Sunflower Bouquet.png', '/images/products/img-130.png', '/images/products/img-132.png'], description: 'Large premium sunflower bouquet', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 12, name: 'Maroon Lily Duo', price: '₹999', image: '/images/products/PremiumBouquet_ Maroon lily Duo.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Red/Maroon', images: ['/images/products/PremiumBouquet_ Maroon lily Duo.png', '/images/products/img-134.png', '/images/products/img-135.png'], description: 'Two maroon lilies together', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 13, name: 'Smiley Bouquet (Medium)', price: '₹1630', image: '/images/products/PremiumBouquet_Smiley Bouquet(Medium).png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Purple/Yellow', images: ['/images/products/PremiumBouquet_Smiley Bouquet(Medium).png', '/images/products/Smiley Bouquet 2nd pic.png', '/images/products/img-138.png'], description: 'Medium premium smiley bouquet', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 15, name: 'Maroon Lily Garden', price: '₹1550', image: '/images/products/PremiumBouquet_Maroon Lily Garden.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Maroon/White', images: ['/images/products/PremiumBouquet_Maroon Lily Garden.png', '/images/products/img-143.png', '/images/products/img-144.png'], description: 'Maroon lily garden arrangement', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 16, name: 'Red Rose Love', price: '₹1650', image: '/images/products/PremiumBouquet_Red Rose love.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Red', images: ['/images/products/PremiumBouquet_Red Rose love.png', '/images/products/img-029.png', '/images/products/img-045.png'], description: 'Premium red roses arrangement', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 17, name: 'Blue Paradise Bouquet (Large)', price: '₹2100', image: '/images/products/PremiumBouquet_Blue Paradise Bouquet.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Blue/White', images: ['/images/products/PremiumBouquet_Blue Paradise Bouquet.png', '/images/products/img-055.png', '/images/products/img-027.png'], description: 'Large blue paradise collection', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 18, name: 'Premium Smiley Bouquet (Large)', price: '₹1899', image: '/images/products/PremiumBouquet_Premium Smiley Bouquet (Large).png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Purple/Yellow', images: ['/images/products/PremiumBouquet_Premium Smiley Bouquet (Large).png', '/images/products/PremiumBouquet_Premium Smiley Bouquet (Large) (2nd image).png', '/images/products/PremiumBouquet_Premium Smiley Bouquet (Large) (3rd image).png', '/images/products/PremiumBouquet_Premium Smiley Bouquet (Large) (4th image).png'], description: 'Large premium smiley arrangement', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 19, name: 'Purple Garden Elegance', price: '₹2500', image: '/images/products/PremiumBouquet_Purple Garden Elegance .png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Purple/White', images: ['/images/products/PremiumBouquet_Purple Garden Elegance .png', '/images/products/img-110.png', '/images/products/img-076.png'], description: 'Elegant purple garden bouquet', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
      { id: 20, name: 'Bluebell Dreams', price: '₹1780', image: '/images/products/PremiumBouquet_Bluebell Dreams.png', category: 'Flowers & Bouquets', subcategory: 'Premium Bouquet Collection', color: 'Blue/White', images: ['/images/products/PremiumBouquet_Bluebell Dreams.png', '/images/products/img-106.png', '/images/products/img-083.png'], description: 'Dreamy bluebell collection', tat: '5-6 hours per flower', care: 'Keep away from direct sunlight' },
    ],
  },
  'Accessories': {
    'Hair & Occasion': [
      { id: 21, name: 'Mohabbat Gajra', price: '₹199', image: '/images/products/Accessories_Mohobbat Gajra.png', category: 'Accessories', subcategory: 'Hair & Occasion', color: 'Cream', images: ['/images/products/Accessories_Mohobbat Gajra.png', '/images/products/img-126.png', '/images/products/img-127.png'], description: 'For the softest of occasions - Thin gajra with green cord', tat: '1-2 hours', care: 'Handle with care' },
      { id: 22, name: 'Pinkish Parandi', price: '₹280', image: '/images/products/Accessories_ Pink Parandi.png', category: 'Accessories', subcategory: 'Hair & Occasion', color: 'Pink/White', images: ['/images/products/Accessories_ Pink Parandi.png', '/images/products/Accessories_ Pink Parandi (2nd image).png', '/images/products/img-130.png'], description: 'Playful pink tassels - For weddings & festivities', tat: '2-3 hours', care: 'Handle with care' },
      { id: 23, name: 'Ivory Bloom Tie', price: '₹120', image: '/images/products/Accessories_Ivory Bloom Tie.png', category: 'Accessories', subcategory: 'Hair & Occasion', color: 'White', images: ['/images/products/Accessories_Ivory Bloom Tie.png', '/images/products/img-133.png', '/images/products/img-134.png'], description: 'Hair tie - Cluster of ivory blossoms', tat: '1-2 hours', care: 'Handle with care' },
      { id: 24, name: 'Rose Gajra', price: '₹280', image: '/images/products/Accessories_Rose Gajra.png', category: 'Accessories', subcategory: 'Hair & Occasion', color: 'Red', images: ['/images/products/Accessories_Rose Gajra.png', '/images/products/img-136.png', '/images/products/img-137.png'], description: 'Rosy red gajra - For weddings & festivities', tat: '2-3 hours', care: 'Handle with care' },
      { id: 25, name: 'Mohabbat Gajra 2.0', price: '₹299', image: '/images/products/Accessories_Mohobbat Gajra 2.0.png', category: 'Accessories', subcategory: 'Hair & Occasion', color: 'Maroon/White', images: ['/images/products/Accessories_Mohobbat Gajra 2.0.png', '/images/products/img-139.png', '/images/products/img-140.png'], description: 'Heavy creamy florals - For special occasions', tat: '2-3 hours', care: 'Handle with care' },
    ],
    'Scrunchies & Everyday': [
      { id: 26, name: 'Blooming Scrunchy', price: '₹220', image: '/images/products/Accessories_Bloom Scrunchies.png', category: 'Accessories', subcategory: 'Scrunchies & Everyday', color: 'Multiple', images: ['/images/products/Accessories_Bloom Scrunchies.png', '/images/products/img-142.png', '/images/products/img-143.png'], description: 'Fluffy petals bloom around wrist - Custom colors available', tat: '1-2 hours', care: 'Gentle wash' },
      { id: 27, name: 'Hearty Scrunchy', price: '₹199', image: '/images/products/Accessories_Hearty Scrunchy.png', category: 'Accessories', subcategory: 'Scrunchies & Everyday', color: 'Pink', images: ['/images/products/Accessories_Hearty Scrunchy.png', '/images/products/img-145.png', '/images/products/img-029.png'], description: 'Sweet soft gentle petals - Custom colors available', tat: '1-2 hours', care: 'Gentle wash' },
      { id: 28, name: 'Flowery Scrunchy', price: '₹299', image: '/images/products/Accessories_Flower Scrunchy.png', category: 'Accessories', subcategory: 'Scrunchies & Everyday', color: 'Purple', images: ['/images/products/Accessories_Flower Scrunchy.png', '/images/products/img-056.png', '/images/products/img-055.png'], description: 'Statement scrunchy with ruffle-garden feel - Custom colors available', tat: '1-2 hours', care: 'Gentle wash' },
      { id: 29, name: 'Pinteresty Basic', price: '₹99', image: '/images/products/Accessories_Pinteresty Basic Scrunchy.png', category: 'Accessories', subcategory: 'Scrunchies & Everyday', color: 'Neutral', images: ['/images/products/Accessories_Pinteresty Basic Scrunchy.png', '/images/products/img-109.png', '/images/products/img-026.png'], description: 'Everyday scrunchies in go-with-everything neutrals - Custom colors available', tat: '1-2 hours', care: 'Gentle wash' },
      { id: 30, name: 'Minimal Scrunchy', price: '₹79', image: '/images/products/Accessories_Minimal Scrunchies.png', category: 'Accessories', subcategory: 'Scrunchies & Everyday', color: 'Multiple', images: ['/images/products/Accessories_Minimal Scrunchies.png', '/images/products/Accessories_Minimal Scrunchies (2nd image).png', '/images/products/img-110.png'], description: 'Simple soft endlessly wearable - Custom colors available', tat: '1-2 hours', care: 'Gentle wash' },
    ],
  },
  'Home Decor': {
    'Decor Collection': [
      { id: 31, name: 'Daisy Bookmark', price: '₹99', image: '/images/products/HomeDecor_Daisy Bookmark.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'White/Yellow', images: ['/images/products/HomeDecor_Daisy Bookmark.png', '/images/products/HomeDecor_Daisy Bookmark(2nd image).png', '/images/products/img-034.png'], description: 'Reading companion - Tiny crochet daisy to hold your page', tat: '2-3 hours', care: 'Dust gently' },
      { id: 32, name: 'Sunflower Pot', price: '₹380', image: '/images/products/HomeDecor_Sunflower Pot.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Yellow', images: ['/images/products/HomeDecor_Sunflower Pot.png', '/images/products/img-131.png', '/images/products/img-107.png'], description: 'Desk bloom - A sunflower that never fades in cosy knit pot', tat: '3-4 hours', care: 'Dust gently' },
      { id: 33, name: 'Lily Flower Pot', price: '₹520', image: '/images/products/HomeDecor_Lily Flower Pot.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Multiple', images: ['/images/products/HomeDecor_Lily Flower Pot.png', '/images/products/HomeDecor_Lily Flower Pot(2nd image).png', '/images/products/img-036.png'], description: 'Desk bloom - 7-8 inch tall - Multiple colors available', tat: '4-5 hours', care: 'Dust gently' },
      { id: 34, name: 'Smiley Bag Charm', price: '₹380', image: '/images/products/HomeDecor_Smiley Bag Charm.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Multi', images: ['/images/products/HomeDecor_Smiley Bag Charm.png', '/images/products/img-084.png', '/images/products/img-097.png'], description: 'Cute bag charm accessory', tat: '2-3 hours', care: 'Handle with care' },
      { id: 35, name: 'Bush Bloom Curtain Holder', price: '₹730', image: '/images/products/HomeDecor_Bush Bloom Curtain Holder.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Multiple', images: ['/images/products/HomeDecor_Bush Bloom Curtain Holder.png', '/images/products/img-114.png', '/images/products/img-111.png'], description: 'Pair with tassels - Soft marble printed large flower', tat: '4-5 hours', care: 'Dust gently' },
      { id: 36, name: 'Sunflower Curtain Holder', price: '₹699', image: '/images/products/HomeDecor_Sunflower Curtain Holder.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Yellow', images: ['/images/products/HomeDecor_Sunflower Curtain Holder.png', '/images/products/img-125.png', '/images/products/img-126.png'], description: 'Pair - Trailing stems - Cascading sunflowers on trailing stem', tat: '4-5 hours', care: 'Dust gently' },
      { id: 38, name: 'Teddy Specs Holder', price: '₹299', image: '/images/products/HomeDecor_Teddy Specs Holder.png', category: 'Home Decor', subcategory: 'Decor Collection', color: 'Brown/Cream', images: ['/images/products/HomeDecor_Teddy Specs Holder.png', '/images/products/HomeDecor_Teddy Specs Holder(2nd Image).png', '/images/products/img-133.png'], description: 'Bedside buddy - Gives your glasses a soft place to rest', tat: '2-3 hours', care: 'Handle with care' },
    ],
  },
};

export const getAllProducts = () => {
  const allProducts = [];
  Object.values(productsData).forEach(category => {
    Object.values(category).forEach(subcategory => {
      allProducts.push(...subcategory);
    });
  });
  return allProducts;
};

export const getProductsByCategory = (categoryName) => {
  return productsData[categoryName] || {};
};
